/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../src/circular-popup-menu.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/forms';
import * as import4 from 'ionic-angular/module';
import * as import5 from '../node_modules/ionic-angular/components/action-sheet/action-sheet-component.ngfactory';
import * as import6 from '../node_modules/ionic-angular/components/alert/alert-component.ngfactory';
import * as import7 from '../node_modules/ionic-angular/components/app/app-root.ngfactory';
import * as import8 from '../node_modules/ionic-angular/components/loading/loading-component.ngfactory';
import * as import9 from '../node_modules/ionic-angular/components/modal/modal-component.ngfactory';
import * as import10 from '../node_modules/ionic-angular/components/picker/picker-component.ngfactory';
import * as import11 from '../node_modules/ionic-angular/components/popover/popover-component.ngfactory';
import * as import12 from '../node_modules/ionic-angular/components/select/select-popover-component.ngfactory';
import * as import13 from '../node_modules/ionic-angular/components/toast/toast-component.ngfactory';
import * as import14 from './circular-menu/circular-menu.ngfactory';
class CircularPopupMenuModuleInjector extends import0.ɵNgModuleInjector<import1.CircularPopupMenuModule> {
  _CommonModule_0:import2.CommonModule;
  _ɵba_1:import3.ɵba;
  _FormsModule_2:import3.FormsModule;
  _ReactiveFormsModule_3:import3.ReactiveFormsModule;
  _IonicModule_4:import4.IonicModule;
  _CircularPopupMenuModule_5:import1.CircularPopupMenuModule;
  __NgLocalization_6:import2.NgLocaleLocalization;
  __ɵi_7:import3.ɵi;
  __FormBuilder_8:import3.FormBuilder;
  constructor(parent:import0.Injector) {
    super(parent,[
      import5.ActionSheetCmpNgFactory,
      import6.AlertCmpNgFactory,
      import7.IonicAppNgFactory,
      import8.LoadingCmpNgFactory,
      import9.ModalCmpNgFactory,
      import10.PickerCmpNgFactory,
      import11.PopoverCmpNgFactory,
      import12.SelectPopoverNgFactory,
      import13.ToastCmpNgFactory,
      import14.CircularMenuPageNgFactory
    ]
    ,([] as any[]));
  }
  get _NgLocalization_6():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_6 == null)) { (this.__NgLocalization_6 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_6;
  }
  get _ɵi_7():import3.ɵi {
    if ((this.__ɵi_7 == null)) { (this.__ɵi_7 = new import3.ɵi()); }
    return this.__ɵi_7;
  }
  get _FormBuilder_8():import3.FormBuilder {
    if ((this.__FormBuilder_8 == null)) { (this.__FormBuilder_8 = new import3.FormBuilder()); }
    return this.__FormBuilder_8;
  }
  createInternal():import1.CircularPopupMenuModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ɵba_1 = new import3.ɵba();
    this._FormsModule_2 = new import3.FormsModule();
    this._ReactiveFormsModule_3 = new import3.ReactiveFormsModule();
    this._IonicModule_4 = new import4.IonicModule();
    this._CircularPopupMenuModule_5 = new import1.CircularPopupMenuModule();
    return this._CircularPopupMenuModule_5;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ɵba)) { return this._ɵba_1; }
    if ((token === import3.FormsModule)) { return this._FormsModule_2; }
    if ((token === import3.ReactiveFormsModule)) { return this._ReactiveFormsModule_3; }
    if ((token === import4.IonicModule)) { return this._IonicModule_4; }
    if ((token === import1.CircularPopupMenuModule)) { return this._CircularPopupMenuModule_5; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_6; }
    if ((token === import3.ɵi)) { return this._ɵi_7; }
    if ((token === import3.FormBuilder)) { return this._FormBuilder_8; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const CircularPopupMenuModuleNgFactory:import0.NgModuleFactory<import1.CircularPopupMenuModule> = new import0.NgModuleFactory<any>(CircularPopupMenuModuleInjector,import1.CircularPopupMenuModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2x1aXNrY3M4OS9Eb2N1bWVudHMvaW9uaWMtY2lyY3VsYXItcG9wdXAtbWVudS9zcmMvY2lyY3VsYXItcG9wdXAtbWVudS5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvbHVpc2tjczg5L0RvY3VtZW50cy9pb25pYy1jaXJjdWxhci1wb3B1cC1tZW51L3NyYy9jaXJjdWxhci1wb3B1cC1tZW51Lm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
